var Constants = function () {
  this.DirectionEnum = {
    DOWN: 0,
    LEFT: 1,
    RIGHT: 2,
    UP: 3
  };

  this.ItemEnum = {
    BLUE_GUARD: 43,
    YELLOW_GUARD: 42,
    RED_PRIEST: 41,
    BLUE_PRIEST: 40,
    BIG_BAT: 39,
    SMALL_BAT: 38,
    ZOMBIE_KNIGHT: 37,
    ZOMBIE_MAN: 36,
    SKELETON_CAPTAIN: 35,
    SKELETON_SOLDIER: 34,
    SKELETON_MAN: 33,
    BLACK_SLIME: 32,
    RED_SLIME: 31,
    GREEN_SLIME: 30,
    WHITE_DOOR: 14,
    IRON_DOOR: 13,
    RED_DOOR: 12,
    BLUE_DOOR: 11,
    YELLOW_DOOR: 10,
    SKY_WALL: 3,
    LAVA_WALL: 2,
    STONE_WALL: 1,
    MAP_FLOOR: 0,
    YELLOW_KEY: -1,
    BLUE_KEY: -2,
    RED_KEY: -3,
    IRON_KEY: -4,
    DOOR_PICK_AXE: -5,
    RED_GEM: -10,
    BLUE_GEM: -11,
    RED_POTION: -12,
    BLUE_POTION: -13,
    SILVER_SWORD: -14,
    IRON_SHIELD: -15,
    SILVER_SHIELD: -16,
    IRON_SWORD: -17,
    HOLLY_WATER: -18,
    STAGE_UP: -97,
    STAGE_DOWN: -98,
    BLUE_STONE: -99
  };
};
